version: '3.4'

services:
  html:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
    command: asciidoctor -n gcw-dm-guidelines.adoc

  pdf:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
    command: asciidoctor-pdf -a pdf-themesdir=./ -a pdf-theme=gcw -n gcw-dm-guidelines.adoc
